# -*- coding: utf-8 -*-
"""สำเนาของ ยินดีต้อนรับสู่ Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aDBCf0puJnUjT_wQ-x5MEGeYVnEzK1IY
"""

FE = 3.5
GB = 2
IS = 3
CP = 4
print("-------- Your Score --------")
print("Foundation English                       >>",FE)
print("General Business                          >>",GB)
print("Introduction to Computer Systems >>",IS)
print("Computer Programming                >>",CP)

#Foundation English
#General Business
#Introduction to Computer Systems
#Computer Programming